name = "albacete-eye-clinic"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding       = "DB"
database_name = "albacete-clinic-db"
database_id   = "a24ab207-9cca-46be-921a-e955b7b56899"
